/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.event.*;
import java.awt.Component;
/**
 *
 * @author hieud
 */
public class GUI_Login extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form login
     */
    public GUI_Login() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        usernameForm = new javax.swing.JLabel();
        passwordForm = new javax.swing.JLabel();
        shopQuanAoIcon = new javax.swing.JLabel();
        backgroundImg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("MẬT KHẨU");
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 240, 30));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("TÊN ĐĂNG NHẬP");
        txtUsername.setBorder(null);
        txtUsername.setOpaque(false);
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 250, 50));

        btnDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.setBorder(null);
        btnDangNhap.setBorderPainted(false);
        btnDangNhap.setMaximumSize(new java.awt.Dimension(1000, 1005));
        btnDangNhap.setMinimumSize(new java.awt.Dimension(300, 45));
        btnDangNhap.setPreferredSize(new java.awt.Dimension(300, 45));
        
        add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 300, 50));

        usernameForm.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\Username.png")); // NOI18N
        add(usernameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        passwordForm.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\Password.png")); // NOI18N
        add(passwordForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        shopQuanAoIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\shopQuanAo.png")); // NOI18N
        add(shopQuanAoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        backgroundImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\BG.png")); // NOI18N
        backgroundImg.setFocusable(false);
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

                                               
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel passwordForm;
    private javax.swing.JLabel shopQuanAoIcon;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel usernameForm;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Component source=(Component)e.getSource();
		source.getParent().dispatchEvent(e);
	  }
}
