/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class GUI_ChiTietDonHang extends javax.swing.JPanel {

    /**
     * Creates new form GUI_ChiTietDonHang
     */
    public GUI_ChiTietDonHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXacNhan = new javax.swing.JButton();
        lblChiTietDonHang = new javax.swing.JLabel();
        panelTTKH = new javax.swing.JPanel();
        lblDCKH = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblSDTKH = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        panelTTDH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTTDH = new javax.swing.JTable();
        panelTTTT = new javax.swing.JPanel();
        lblTong = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblGiamGia = new javax.swing.JLabel();
        lblPhiVanChuyen = new javax.swing.JLabel();
        lblGiamGiaTien = new javax.swing.JLabel();
        lblPhiVanChuyenTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnXacNhan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnXacNhan.setText("XÁC NHẬN");
        add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, -1, -1));

        lblChiTietDonHang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblChiTietDonHang.setText("CHI TIẾT ĐƠN HÀNG");
        add(lblChiTietDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 11, -1, -1));

        panelTTKH.setBackground(new java.awt.Color(255, 255, 255));
        panelTTKH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblDCKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDCKH.setText("123 Nguyễn Thái Sơn, Phường 5, Quận Gò Vấp, TPHCM");

        lblDiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");

        lblSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSDT.setText("Số điện thoại:");

        lblSDTKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSDTKH.setText("0123456789");

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTen.setText("Nguyễn Văn A");

        lblHoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHoTen.setText("Họ tên:");

        javax.swing.GroupLayout panelTTKHLayout = new javax.swing.GroupLayout(panelTTKH);
        panelTTKH.setLayout(panelTTKHLayout);
        panelTTKHLayout.setHorizontalGroup(
            panelTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTKHLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTTKHLayout.createSequentialGroup()
                        .addComponent(lblHoTen)
                        .addGap(93, 93, 93)
                        .addComponent(lblTen))
                    .addGroup(panelTTKHLayout.createSequentialGroup()
                        .addComponent(lblSDT)
                        .addGap(42, 42, 42)
                        .addComponent(lblSDTKH))
                    .addGroup(panelTTKHLayout.createSequentialGroup()
                        .addComponent(lblDiaChi)
                        .addGap(92, 92, 92)
                        .addComponent(lblDCKH)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        panelTTKHLayout.setVerticalGroup(
            panelTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTTKHLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panelTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTen)
                    .addComponent(lblTen))
                .addGap(18, 18, 18)
                .addGroup(panelTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSDT)
                    .addComponent(lblSDTKH))
                .addGap(18, 18, 18)
                .addGroup(panelTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaChi)
                    .addComponent(lblDCKH))
                .addGap(26, 26, 26))
        );

        add(panelTTKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 940, 190));

        panelTTDH.setBackground(new java.awt.Color(255, 255, 255));
        panelTTDH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tableTTDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số lượng", "Tên sản phẩm", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTTDH);
        if (tableTTDH.getColumnModel().getColumnCount() > 0) {
            tableTTDH.getColumnModel().getColumn(0).setResizable(false);
            tableTTDH.getColumnModel().getColumn(1).setResizable(false);
            tableTTDH.getColumnModel().getColumn(2).setResizable(false);
            tableTTDH.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout panelTTDHLayout = new javax.swing.GroupLayout(panelTTDH);
        panelTTDH.setLayout(panelTTDHLayout);
        panelTTDHLayout.setHorizontalGroup(
            panelTTDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTDHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTTDHLayout.setVerticalGroup(
            panelTTDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTDHLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        add(panelTTDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 940, 210));

        panelTTTT.setBackground(new java.awt.Color(255, 255, 255));
        panelTTTT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thanh toán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblTong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTong.setForeground(new java.awt.Color(255, 51, 51));
        lblTong.setText("Tổng:");

        lblTongTien.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTongTien.setText("1.180.000đ");

        lblGiamGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGiamGia.setText("Giảm giá:");

        lblPhiVanChuyen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPhiVanChuyen.setText("Phí vận chuyển:");

        lblGiamGiaTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGiamGiaTien.setText("0đ");

        lblPhiVanChuyenTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPhiVanChuyenTien.setText("30.000đ");

        javax.swing.GroupLayout panelTTTTLayout = new javax.swing.GroupLayout(panelTTTT);
        panelTTTT.setLayout(panelTTTTLayout);
        panelTTTTLayout.setHorizontalGroup(
            panelTTTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTTTTLayout.createSequentialGroup()
                .addContainerGap(492, Short.MAX_VALUE)
                .addGroup(panelTTTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTTTTLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblGiamGia)
                        .addGap(280, 280, 280)
                        .addComponent(lblGiamGiaTien))
                    .addGroup(panelTTTTLayout.createSequentialGroup()
                        .addComponent(lblPhiVanChuyen)
                        .addGap(235, 235, 235)
                        .addComponent(lblPhiVanChuyenTien))
                    .addGroup(panelTTTTLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblTong)
                        .addGap(181, 181, 181)
                        .addComponent(lblTongTien)))
                .addContainerGap())
        );
        panelTTTTLayout.setVerticalGroup(
            panelTTTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTTTLayout.createSequentialGroup()
                .addGroup(panelTTTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGiamGia)
                    .addComponent(lblGiamGiaTien))
                .addGap(18, 18, 18)
                .addGroup(panelTTTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhiVanChuyen)
                    .addComponent(lblPhiVanChuyenTien))
                .addGap(18, 18, 18)
                .addGroup(panelTTTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTong)
                    .addComponent(lblTongTien))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        add(panelTTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 940, 150));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChiTietDonHang;
    private javax.swing.JLabel lblDCKH;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lblGiamGiaTien;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblPhiVanChuyen;
    private javax.swing.JLabel lblPhiVanChuyenTien;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSDTKH;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTong;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel panelTTDH;
    private javax.swing.JPanel panelTTKH;
    private javax.swing.JPanel panelTTTT;
    private javax.swing.JTable tableTTDH;
    // End of variables declaration//GEN-END:variables
}
