/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class GUI_ThemSuaQuanAo extends javax.swing.JPanel {

    /**
     * Creates new form GUI_ThemSuaQuanAo
     */
    public GUI_ThemSuaQuanAo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lblTacVu = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        lblHang = new javax.swing.JLabel();
        txtHang = new javax.swing.JTextField();
        txtLoai = new javax.swing.JTextField();
        lblLoai = new javax.swing.JLabel();
        txtXuatXu = new javax.swing.JTextField();
        lblXuatXu = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        lblThongTin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtThongTin = new javax.swing.JTextArea();
        lblHinhAnh = new javax.swing.JLabel();
        txtHinhAnh = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTacVu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTacVu.setText("THÊM SẢN PHẨM");
        add(lblTacVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 35, -1, -1));

        lblTenSP.setText("Tên Sản phẩm:");
        add(lblTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 106, -1, -1));
        add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 103, 191, -1));

        lblHang.setText("Hãng sản xuất:");
        add(lblHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 106, -1, -1));
        add(txtHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 103, 191, -1));
        add(txtLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 155, 191, -1));

        lblLoai.setText("Loại:");
        add(lblLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 158, -1, -1));
        add(txtXuatXu, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 155, 191, -1));

        lblXuatXu.setText("Xuất xứ:");
        add(lblXuatXu, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 158, -1, -1));
        add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 216, 191, -1));

        lblSoLuong.setText("Số lượng:");
        add(lblSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 219, -1, -1));
        add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 216, 191, -1));

        lblDonGia.setText("Đơn giá:");
        add(lblDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 219, -1, -1));

        lblThongTin.setText("Thông tin:");
        add(lblThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 273, -1, -1));

        txtThongTin.setColumns(20);
        txtThongTin.setRows(5);
        jScrollPane1.setViewportView(txtThongTin);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 273, 546, 106));

        lblHinhAnh.setText("Hình ảnh:");
        add(lblHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 400, -1, -1));
        add(txtHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 397, 191, -1));

        btnThem.setText("THÊM");
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 435, 128, 38));

        btnHuy.setText("HỦY");
        add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 435, 128, 38));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblHang;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTacVu;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JLabel lblXuatXu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtHang;
    private javax.swing.JTextField txtHinhAnh;
    private javax.swing.JTextField txtLoai;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextArea txtThongTin;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
