/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class GUI_InfoQuanAo extends javax.swing.JPanel {

    /**
     * Creates new form panelQuanAoInfo
     */
    public GUI_InfoQuanAo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThemVaoGio = new javax.swing.JButton();
        lblTenSP = new javax.swing.JLabel();
        anhSP = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblHang = new javax.swing.JLabel();
        lblLoai = new javax.swing.JLabel();
        lblXuatXu = new javax.swing.JLabel();
        lblChatLieu = new javax.swing.JLabel();
        lblThongTin = new javax.swing.JLabel();
        lblKichThuoc = new javax.swing.JLabel();
        btnS = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnXL = new javax.swing.JButton();
        lblTenHang = new javax.swing.JLabel();
        lblTenLoai = new javax.swing.JLabel();
        lblTenXuatXu = new javax.swing.JLabel();
        lblTenChatLieu = new javax.swing.JLabel();
        btnMuaNgay = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(800, 500));

        btnThemVaoGio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemVaoGio.setText("THÊM VÀO GIỎ HÀNG");

        lblTenSP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTenSP.setText("ÁO SAMPLE");

        anhSP.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\ao\\1a.png")); // NOI18N
        anhSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblGia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblGia.setForeground(new java.awt.Color(255, 51, 51));
        lblGia.setText("350.000đ");

        lblHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHang.setText("Hãng:");

        lblLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLoai.setText("Loại:");

        lblXuatXu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblXuatXu.setText("Xuất xứ:");

        lblChatLieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChatLieu.setText("Chất liệu:");

        lblThongTin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThongTin.setText("Thông tin:");

        lblKichThuoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKichThuoc.setText("Kích thước:");

        btnS.setText("S");
        btnS.setPreferredSize(new java.awt.Dimension(50, 50));

        btnM.setText("M");
        btnM.setPreferredSize(new java.awt.Dimension(50, 50));

        btnL.setText("L");
        btnL.setPreferredSize(new java.awt.Dimension(50, 50));

        btnXL.setText("XL");
        btnXL.setPreferredSize(new java.awt.Dimension(50, 50));

        lblTenHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenHang.setText("Bad Habits");

        lblTenLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenLoai.setText("Áo");

        lblTenXuatXu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenXuatXu.setText("Việt Nam");

        lblTenChatLieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenChatLieu.setText("Cotton");

        btnMuaNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMuaNgay.setText("MUA NGAY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(anhSP)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblTenSP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLoai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTenLoai))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTenHang))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblXuatXu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTenXuatXu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChatLieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTenChatLieu))
                    .addComponent(lblThongTin)
                    .addComponent(lblKichThuoc)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMuaNgay)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGia)
                            .addComponent(btnThemVaoGio))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTenSP)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHang)
                            .addComponent(lblTenHang))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoai)
                            .addComponent(lblTenLoai))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblXuatXu)
                            .addComponent(lblTenXuatXu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChatLieu)
                            .addComponent(lblTenChatLieu))
                        .addGap(18, 18, 18)
                        .addComponent(lblThongTin)
                        .addGap(34, 34, 34)
                        .addComponent(lblKichThuoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnM, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(btnL, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(btnXL, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblGia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemVaoGio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMuaNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(anhSP)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhSP;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnMuaNgay;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnThemVaoGio;
    private javax.swing.JButton btnXL;
    private javax.swing.JLabel lblChatLieu;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblHang;
    private javax.swing.JLabel lblKichThuoc;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblTenChatLieu;
    private javax.swing.JLabel lblTenHang;
    private javax.swing.JLabel lblTenLoai;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTenXuatXu;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JLabel lblXuatXu;
    // End of variables declaration//GEN-END:variables
}
