/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class GUI_QuanAoPanel extends javax.swing.JPanel {

    /**
     * Creates new form quanAoPanel
     */
    public GUI_QuanAoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimKiem = new javax.swing.JTextField();
        searchBox = new javax.swing.JLabel();
        scrollGrid = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        quanAoUI1 = new gui.GUI_QuanAoComponent();
        quanAoUI2 = new gui.GUI_QuanAoComponent();
        quanAoUI3 = new gui.GUI_QuanAoComponent();
        quanAoUI4 = new gui.GUI_QuanAoComponent();
        quanAoUI5 = new gui.GUI_QuanAoComponent();
        quanAoUI6 = new gui.GUI_QuanAoComponent();
        quanAoUI7 = new gui.GUI_QuanAoComponent();
        quanAoUI8 = new gui.GUI_QuanAoComponent();
        quanAoUI9 = new gui.GUI_QuanAoComponent();
        quanAoUI10 = new gui.GUI_QuanAoComponent();
        quanAoUI11 = new gui.GUI_QuanAoComponent();
        quanAoUI12 = new gui.GUI_QuanAoComponent();
        quanAoUI13 = new gui.GUI_QuanAoComponent();
        quanAoUI14 = new gui.GUI_QuanAoComponent();
        quanAoUI15 = new gui.GUI_QuanAoComponent();
        quanAoUI16 = new gui.GUI_QuanAoComponent();
        quanAoUI17 = new gui.GUI_QuanAoComponent();
        quanAoUI18 = new gui.GUI_QuanAoComponent();
        quanAoUI19 = new gui.GUI_QuanAoComponent();
        quanAoUI20 = new gui.GUI_QuanAoComponent();
        scrollList = new javax.swing.JScrollPane();
        tableQuanAo = new javax.swing.JTable();
        btnDsQA = new javax.swing.JButton();
        btnLuoi = new javax.swing.JButton();
        btnTimKiem1 = new javax.swing.JButton();
        btnThemSP1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.setBorder(null);
        txtTimKiem.setOpaque(false);
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 260, 50));

        searchBox.setIcon(new javax.swing.ImageIcon("resources\\search.png"));
        add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        scrollGrid.setBackground(new java.awt.Color(255, 255, 255));
        scrollGrid.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(835, 1000));
        jPanel1.setLayout(new java.awt.GridLayout(4, 5, 40, 20));

        quanAoUI1.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI1);

        quanAoUI2.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI2);

        quanAoUI3.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI3);

        quanAoUI4.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI4);

        quanAoUI5.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI5);

        quanAoUI6.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI6);

        quanAoUI7.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI7);

        quanAoUI8.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI8);

        quanAoUI9.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI9);

        quanAoUI10.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI10);

        quanAoUI11.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI11);

        quanAoUI12.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI12);

        quanAoUI13.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI13);

        quanAoUI14.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI14);

        quanAoUI15.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI15);

        quanAoUI16.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI16);

        quanAoUI17.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI17);

        quanAoUI18.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI18);

        quanAoUI19.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI19);

        quanAoUI20.setPreferredSize(new java.awt.Dimension(151, 200));
        jPanel1.add(quanAoUI20);

        scrollGrid.setViewportView(jPanel1);

        add(scrollGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 960, 570));

        tableQuanAo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên sản phẩm", "Thương hiệu", "Đơn giá", "Tồn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuanAo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableQuanAo.setCellSelectionEnabled(true);
        tableQuanAo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableQuanAo.setRowHeight(30);
        tableQuanAo.setShowGrid(true);
        scrollList.setViewportView(tableQuanAo);

        add(scrollList, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 960, 570));

        btnDsQA.setBackground(new java.awt.Color(255, 255, 255));
        btnDsQA.setIcon(new javax.swing.ImageIcon("resources\\grid.png"));
        btnDsQA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(btnDsQA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 50, 45));

        btnLuoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLuoi.setIcon(new javax.swing.ImageIcon("resources\\list.png"));
        btnLuoi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnLuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuoiActionPerformed(evt);
            }
        });
        add(btnLuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 50, 45));

        btnTimKiem1.setBackground(new java.awt.Color(255, 255, 255));
        btnTimKiem1.setText("Tìm kiếm");
        btnTimKiem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(btnTimKiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 86, 45));

        btnThemSP1.setBackground(new java.awt.Color(255, 255, 255));
        btnThemSP1.setText("Thêm sản phẩm");
        btnThemSP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(btnThemSP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 60, 120, 45));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDsQA;
    private javax.swing.JButton btnLuoi;
    private javax.swing.JButton btnThemSP1;
    private javax.swing.JButton btnTimKiem1;
    private javax.swing.JPanel jPanel1;
    private gui.GUI_QuanAoComponent quanAoUI1;
    private gui.GUI_QuanAoComponent quanAoUI10;
    private gui.GUI_QuanAoComponent quanAoUI11;
    private gui.GUI_QuanAoComponent quanAoUI12;
    private gui.GUI_QuanAoComponent quanAoUI13;
    private gui.GUI_QuanAoComponent quanAoUI14;
    private gui.GUI_QuanAoComponent quanAoUI15;
    private gui.GUI_QuanAoComponent quanAoUI16;
    private gui.GUI_QuanAoComponent quanAoUI17;
    private gui.GUI_QuanAoComponent quanAoUI18;
    private gui.GUI_QuanAoComponent quanAoUI19;
    private gui.GUI_QuanAoComponent quanAoUI2;
    private gui.GUI_QuanAoComponent quanAoUI20;
    private gui.GUI_QuanAoComponent quanAoUI3;
    private gui.GUI_QuanAoComponent quanAoUI4;
    private gui.GUI_QuanAoComponent quanAoUI5;
    private gui.GUI_QuanAoComponent quanAoUI6;
    private gui.GUI_QuanAoComponent quanAoUI7;
    private gui.GUI_QuanAoComponent quanAoUI8;
    private gui.GUI_QuanAoComponent quanAoUI9;
    private javax.swing.JScrollPane scrollGrid;
    private javax.swing.JScrollPane scrollList;
    private javax.swing.JLabel searchBox;
    private javax.swing.JTable tableQuanAo;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
