/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class GUI_Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public GUI_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDiaChi = new javax.swing.JTextField();
        diaChi = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        sdt = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        fullname = new javax.swing.JLabel();
        txtRetypePassword = new javax.swing.JTextField();
        reTypePass = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        passwordForm = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        usernameForm = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        shopQuanAoIcon = new javax.swing.JLabel();
        backgroundImg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        txtDiaChi.setText("ĐỊA CHỈ");
        txtDiaChi.setBorder(null);
        txtDiaChi.setOpaque(false);
        add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 250, 50));

        diaChi.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\diachi.png")); // NOI18N
        add(diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSDT.setForeground(new java.awt.Color(255, 255, 255));
        txtSDT.setText("SỐ ĐIỆN THOẠI");
        txtSDT.setBorder(null);
        txtSDT.setOpaque(false);
        add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 250, 50));

        sdt.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\sdt.png")); // NOI18N
        add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        txtFullname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFullname.setForeground(new java.awt.Color(255, 255, 255));
        txtFullname.setText("HỌ VÀ TÊN");
        txtFullname.setBorder(null);
        txtFullname.setOpaque(false);
        add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 250, 50));

        fullname.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\Username.png")); // NOI18N
        add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        txtRetypePassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRetypePassword.setForeground(new java.awt.Color(255, 255, 255));
        txtRetypePassword.setText("NHẬP LẠI MẬT KHẨU");
        txtRetypePassword.setBorder(null);
        txtRetypePassword.setOpaque(false);
        add(txtRetypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 240, 30));

        reTypePass.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\Password.png")); // NOI18N
        add(reTypePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("MẬT KHẨU");
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 240, 30));

        passwordForm.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\Password.png")); // NOI18N
        add(passwordForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("TÊN ĐĂNG NHẬP");
        txtUsername.setBorder(null);
        txtUsername.setOpaque(false);
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 250, 50));

        usernameForm.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\Username.png")); // NOI18N
        add(usernameForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("ĐĂNG KÝ");
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.setMaximumSize(new java.awt.Dimension(1000, 1005));
        btnRegister.setMinimumSize(new java.awt.Dimension(300, 45));
        btnRegister.setPreferredSize(new java.awt.Dimension(300, 45));
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 300, 50));

        shopQuanAoIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\shopQuanAo.png")); // NOI18N
        add(shopQuanAoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        backgroundImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\hieud\\Documents\\NetBeansProjects\\ShopQuanAo\\resources\\BG.png")); // NOI18N
        backgroundImg.setFocusable(false);
        add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel diaChi;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel passwordForm;
    private javax.swing.JLabel reTypePass;
    private javax.swing.JLabel sdt;
    private javax.swing.JLabel shopQuanAoIcon;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRetypePassword;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel usernameForm;
    // End of variables declaration//GEN-END:variables
}
